default: &default
  store: memory_store
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  store: redis_cache_store
  url: <%= ENV["REDIS_URL"] %>
  store_options:
    namespace: <%= Rails.env %>
