default: &default
  store: redis_cache_store
  url: <%= ENV["REDIS_CACHE_URL"] %>
  namespace: <%= Rails.env %>
  compress: true
  pool_size: 5
  expires_in: 1.hour

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
