default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: beepi_development
  username: postgres
  password: 

test:
  <<: *default
  database: beepi_test

production:
  primary:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
