production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *primary_production
    database: beepicc_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: beepicc_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: beepicc_cable
    migrations_paths: db/cable_migrate
