default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  primary:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
